name: flutter_plate_2
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  animations: ^2.0.0
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.2.2
  file_picker: ^3.0.3
  firebase_auth: ^1.4.1
  firebase_messaging: ^10.0.2
  firebase_storage: ^8.1.3
  fl_chart: ^0.36.2
  flutter:
    sdk: flutter
  flutter_local_notifications: ^6.0.0
  flutter_screenutil: ^5.0.0+2
  flutter_slidable: ^0.6.0
  flutter_svg: ^0.22.0
  font_awesome_flutter: ^9.1.0
  get: ^4.1.4
  getwidget: ^2.0.2
  google_fonts: ^2.1.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  introduction_screen: ^2.1.0
  logger: ^1.0.0
  package_info_plus: ^1.0.3
  path_provider: ^2.0.2
  permission_handler: ^8.1.2
  sentry_flutter: ^5.1.0
  settings_ui: ^1.0.0
  share: ^2.0.4
  timeago: ^3.1.0
  url_launcher: ^6.0.7

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  build_runner: ^2.0.5
  flutter_flavorizr: ^2.0.0
  flutter_native_splash: ^1.2.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

flavorizr:
  app:
    android:
      flavorDimensions: "flavor-type"
    ios:

  flavors:
    development:
      app:
        name: "Flutter Plate (Dev)"
      android:
        applicationId: "com.genericslab.flutterplate.dev"
        firebase:
          config: "firebase/development/google-services.json"
      ios:
        bundleId: "com.genericslab.flutterplate.dev"
        firebase:
          config: "firebase/development/GoogleService-Info.plist"

    staging:
      app:
        name: "Flutter Plate (Stg)"
      android:
        applicationId: "com.genericslab.flutterplate.stg"
        firebase:
          config: "firebase/staging/google-services.json"
      ios:
        bundleId: "com.genericslab.flutterplate.stg"
        firebase:
          config: "firebase/staging/GoogleService-Info.plist"

    early:
      app:
        name: "Flutter Plate (Early)"
      android:
        applicationId: "com.genericslab.flutterplate.erly"
        firebase:
          config: "firebase/early/google-services.json"
      ios:
        bundleId: "com.genericslab.flutterplate.erly"
        firebase:
          config: "firebase/early/GoogleService-Info.plist"

    production:
      app:
        name: "Flutter Plate"
      android:
        applicationId: "com.genericslab.flutterplate"
        firebase:
          config: "firebase/production/google-services.json"
      ios:
        bundleId: "com.genericslab.flutterplate"
        firebase:
          config: "firebase/production/GoogleService-Info.plist"

  assetsUrl: "https://github.com/AngeloAvv/flutter_flavorizr/releases/download/v2.0.0/assets.zip"
  ide: "idea"